env: "prod" #* local, dev, prod
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "myuser"
  password: "mypass"
app_secret: "test-secret"
clients:
  sso:
    address: "localhost:8083"
    timeout: 5s
    retries_count: 5